//=================================================================================
// Yaskawa Italia Srl
//(c)Copyright Yaskawa Italia Srl All Rights Reserved
//---------------------------------------------------------------------------------
// 
// Tested with: iC9226M-FSoE
// Engineering: iCube Engineer 2025.6 (Build 7.2.38936.0)
// Requirements: iC9226M-EC / iC9226M-FSoE
// Functionality: manage axis
//---------------------------------------------------------------------------------
// Change log table:
// Version   Date         Expert in charge                     Changes applied
// 0.00.01   10-07-2025   Fsarta(Francesco.sarta@yaskawa.eu)   New Version Released
//=================================================================================

(*
fbErrorHandler(
    bResetErrors := G_bResetAllErrors, 
    bAcknowledgeErrors := G_bAcknowledgeAllErrors
    );
*)    